language: c
os:
- linux
- osx
sudo: false
compiler:
- gcc
- clang
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- conda install glib -c conda-forge
- mkdir _build && cd _build
- cmake .. -DCMAKE_INSTALL_PREFIX=$HOME -DCMAKE_BUILD_TYPE=Release
- make all
- make install
script:
- ls $TRAVIS_BUILD_DIR/_build/testing/test-*
- gtester $TRAVIS_BUILD_DIR/_build/testing/test-*
- which cem
- cem --help
- cem --version
  # - cem
