language: c
os:
- linux
- osx
sudo: false
compilers:
- gcc
- clang
install:
- echo "Build on $TRAVIS_OS_NAME"
- mkdir _build
- cd _build
- cmake .. -DCMAKE_INSTALL_PREFIX=$HOME -DCMAKE_BUILD_TYPE=Release
- make all
- make install
script:
- gtester testing/test-*
- which cem
- cem --help
- cem --version
  # - cem
