language: c
os:
- linux
- osx
sudo: false
compiler:
- gcc
- clang
install:
- echo "Build on $TRAVIS_OS_NAME"
- mkdir _build
- cd _build
- cmake .. -DCMAKE_INSTALL_PREFIX=$HOME -DCMAKE_BUILD_TYPE=Release
- make all
- make install
script:
- ls $TRAVIS_BUILD_DIR/_build/testing
- gtester $TRAVIS_BUILD_DIR/_build/testing/test-*
- which cem
- cem --help
- cem --version
  # - cem
