package:
  name: cem
  version: "0.1.5"

source:
  path: ..

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
  host:
    - glib
  run:
    - glib

test:
  commands:
  - deltas --version
  - deltas --help
  - waves --version
  - waves --help
  - cem --version
  - cem --help

about:
  home: https://github.com/csdms-contrib/cem
  license: MIT
  license_file: LICENSE
  summary: The Coastline Evolution Model

build:
  number: 0
